// Dashboard data — auto-generated by generate_data.py
// Last updated: 2026-03-24T12:49:07+07:00
// Source: Google Sheet (Deals + Actions + Contacts tabs)
const DASHBOARD_DATA = {
  "generated_at": "2026-03-24T12:49:07+07:00",
  "sources": {
    "deals": "error",
    "actions": "error",
    "contacts": "error"
  },
  "target": {
    "annual": 150000000,
    "ytd_closed": 0,
    "currency": "THB"
  },
  "stage_weights": {
    "E": 0.05,
    "D": 0.1,
    "C2": 0.25,
    "C1": 0.5,
    "B": 0.75,
    "A": 0.9
  },
  "stage_sla": {
    "E": 14,
    "D": 30,
    "C2": 30,
    "C1": 45,
    "B": 30,
    "A": 14
  },
  "deals": [],
  "i_owe": [],
  "they_owe": [],
  "hit_list": [],
  "metrics": {
    "calls_today": 0,
    "contacts_added": 0,
    "transcripts_processed": 0,
    "emails_queued": 0,
    "deals_at_d_or_above": 0,
    "pipeline_total": null,
    "weighted_total": null
  }
};
