// Dashboard data — generated by refresh.sh
// Last updated: 2026-03-23T16:00:00+07:00
const DASHBOARD_DATA = {
  generated_at: "2026-03-23T16:00:00+07:00",
  sources: { leads: "ok", acp: "ok", tasks: "ok" },
  target: { annual: 150000000, ytd_closed: 0, currency: "THB" },
  stage_weights: { E: 0.05, D: 0.10, C2: 0.25, C1: 0.50, B: 0.75, A: 0.90 },
  stage_sla: { E: 14, D: 30, C2: 30, C1: 45, B: 30, A: 14 },

  deals: [
    {
      id: 1, company: "BFC (Bangkok Fastening)", person: "K. Lek", title: "Purchasing Manager",
      stage: "D", days_at_stage: 5, days_since_contact: 0, value: null, confidence: "hot",
      six_elements: {
        timeline: { status: false, detail: "客戶尚未提及系統上線時程，無明確Go-Live日期。需在提案中提出分階段上線建議" },
        budget: { status: "partial", detail: "家族企業，預算極度保守。報價只有一次機會，報高即被拒絕" },
        requirements: { status: true, detail: "WMS (倉庫盲區)、MES (馬達維修追蹤)、成本計算 (按件計而非按公斤)" },
        decision: { status: true, detail: "K.Lek → 坤Nueng (推動者) → Dr.Chok (副總) → MD (老闆不參加供應商會議)" },
        competitors: { status: "partial", detail: "現用舊版Oracle (由一位IT資深Boonchai維護)。中國製造商正進入市場" },
        motivation: { status: true, detail: "利潤流失且無人知曉去向，中國競爭壓力，Oracle系統風險（僅一人維護）" }
      },
      must_act: "strong", must_act_detail: "利潤持續外漏、中國競爭者現代化、Oracle系統僅一人維護",
      must_choose_digiwin: "weak", must_choose_detail: "尚未建立。提案必須說明為何鼎捷優於Oracle升級或SAP",
      next_action: "Prepare tailored proposal for Khun Nueng",
      pain_points: [
        "倉庫庫存盲區 — Store說沒空間，但物料其實在，只是找不到",
        "馬達維修成本無法追蹤 — 上百顆馬達，送修不知是哪顆",
        "按公斤計成本隱藏真實單件成本 — Dr.Chok說成本OK但利潤不見",
        "舊版Oracle無支援 — Boonchai一人維護，他離職系統就死",
        "家族企業預算保守 — IT投資審批極為困難",
        "中國競爭壓力 — 對手以整合系統+低價進入泰國市場",
        "物料遺失=隱形成本 — 少了一箱沒人知道但還是要付錢"
      ],
      stakeholders: [
        { name: "K. Lek", role: "採購經理", type: "聯絡窗口", notes: "住在Lasalle/Srinakarin，跟Peter是鄰居" },
        { name: "Dr. Treerapot (坤Nueng/蔡漢霖)", role: "CFO 財務長", type: "決策者/Champion", notes: "Ph.D. 推動MES取代人工，將提案給老闆。有預算權。Email: treerapot@bfcthai.com" },
        { name: "Dr. Chok", role: "副總經理", type: "技術決策者", notes: "工程背景，看大局不深入細節" },
        { name: "MD (老闆)", role: "最終決策者", type: "Economic Buyer", notes: "不參加供應商會議，所有提案經坤Nueng" },
        { name: "Boonchai", role: "IT經理", type: "系統管理者", notes: "10-20年資深，獨自維護Oracle" }
      ],
      industry: "螺絲/扣件製造", fit: "HIGH",
      transcript_date: "2026-03-23",
      call_summary: "深度探詢通話。K.Lek揭露BFC七大痛點。44年家族企業面臨中國競爭壓力。Peter建立了個人信任（同社區鄰居）。",
      expected_close_date: null,
      stage_entry_date: "2026-03-23",
      contacts: [
        { name: "K. Lek", phone: "+66898124076", email: null, line: null, role: "採購經理" },
        { name: "Dr. Treerapot", phone: "+6623126159", email: "treerapot@bfcthai.com", line: null, role: "CFO / Champion" }
      ],
      advancement: {
        current: "D", target: "C2",
        checklist: [
          { task: "與決策者(坤Nueng)確認痛點", done: false },
          { task: "開始預算討論（提出分階段報價）", done: false },
          { task: "確認所有競爭對手", done: false },
          { task: "提交初步提案含分階段定價", done: false }
        ]
      },
      six_element_actions: {
        timeline: { action: "在提案中提出分階段上線建議，詢問客戶期望Go-Live時間", due: null },
        budget: { action: "提案中包含分階段報價，讓客戶看到Phase 1最低投入", due: null },
        competitors: { action: "下次通話確認是否有其他供應商在接觸", due: null }
      },
      activity_log: [
        { date: "2026-03-23", action: "與K.Lek深度探詢通話", outcome: "確認7大痛點，建立個人信任", stage_change: "E→D" },
        { date: "2026-03-21", action: "首次現場訪問（坤Nueng, K.Ek, K.Pik）", outcome: "MES興趣確認", stage_change: null }
      ]
    },
    {
      id: 2, company: "Impextraco", person: "Petch Janbanjong", title: "Project Engineer",
      stage: "D", days_at_stage: 0, days_since_contact: 0, value: null, confidence: "warm",
      six_elements: {
        timeline: { status: "partial", detail: "今年內建廠，但尚未確認具體日期" },
        budget: { status: false, detail: "未知" },
        requirements: { status: "partial", detail: "MES系統（從展會諮詢），可能需要完整ERP+WMS" },
        decision: { status: "partial", detail: "比利時管理層（講英文）。Petch是建廠工程師，非最終決策者" },
        competitors: { status: false, detail: "未知" },
        motivation: { status: true, detail: "新建工廠，完全沒有現有系統 — 四大非做不可理由之一！" }
      },
      must_act: "strong", must_act_detail: "新建工廠無系統（四大非做不可理由之一）",
      must_choose_digiwin: "weak", must_choose_detail: "尚未建立。需向比利時管理層展示",
      next_action: "Call Petch Wednesday to schedule presentation",
      pain_points: ["新建工廠完全沒有MES系統", "比利時管理層忙碌經常出差"],
      stakeholders: [
        { name: "Petch", role: "建廠工程師", type: "聯絡窗口", notes: "暱稱Nu" },
        { name: "比利時管理層", role: "決策者", type: "Economic Buyer", notes: "講英文，經常出差" }
      ],
      industry: "動物飼料/飼料原料", fit: "HIGH",
      transcript_date: "2026-03-23",
      call_summary: "電話跟進。比利時公司今年在泰國建新廠。Peter承諾週三回電安排簡報。英文簡報。"
    },
    {
      id: 3, company: "Mitsuya Limited", person: "Yanisa Danchaivijit", title: "Assistant Managing Director",
      stage: "D", days_at_stage: 0, days_since_contact: 0, value: null, confidence: "warm",
      six_elements: {
        timeline: { status: false, detail: "第一階段(網站)現在，第二階段(ERP)之後 — 無具體日期" },
        budget: { status: false, detail: "未知。叔叔猶豫投資" },
        requirements: { status: "partial", detail: "第一階段：網站/電商。第二階段：ERP+MES/WMS" },
        decision: { status: "partial", detail: "70歲叔叔/老闆是唯一決策者。Yanisa(28歲)是推動者。Nattaya管日常" },
        competitors: { status: false, detail: "未知" },
        motivation: { status: "partial", detail: "中國競爭壓力+需要數位存在感。但叔叔抗拒現代化" }
      },
      must_act: "partial", must_act_detail: "中國競爭壓力，但叔叔的抗拒削弱了緊迫性",
      must_choose_digiwin: "weak", must_choose_detail: "尚未建立。鼎捷不做網站（第一階段非我們的機會）",
      next_action: "Send follow-up email to yanisa@mitsuya.co.th",
      pain_points: [
        "嚴重代際衝突 — 70歲叔叔拒絕Wix，要求傳統供應商方式",
        "叔叔微管理、偏執，打印電子郵件閱讀",
        "紙本作業的倉庫和製造流程，依賴資深員工記憶",
        "Yanisa士氣和創造力被傳統環境消耗"
      ],
      stakeholders: [
        { name: "Yanisa (陈慧英)", role: "副總經理", type: "Champion", notes: "28歲，推動數位轉型" },
        { name: "Nattaya (เกล)", role: "行銷協調", type: "操作聯絡人", notes: "管理ERP/網站供應商協調" },
        { name: "叔叔/老闆", role: "最終決策者", type: "Economic Buyer", notes: "70歲，傳統思維，說要退休10年了還沒退" }
      ],
      industry: "汽車零件製造", fit: "HIGH",
      transcript_date: "2026-03-23",
      call_summary: "70分鐘面對面會議。Yanisa揭示深層代際衝突。Peter定位為戰略顧問（非僅ERP供應商）。種下種子：網站需要ERP後端支持。"
    },
    {
      id: 4, company: "Toyota Tsusho Forklift", person: "Chayut Kruekamkhao", title: "Logistics Manager",
      stage: "D", days_at_stage: 0, days_since_contact: 0, value: null, confidence: "warm",
      six_elements: {
        timeline: { status: false, detail: "下週線上會議 — 但無具體專案時程" },
        budget: { status: false, detail: "未知" },
        requirements: { status: true, detail: "AGV/AMR用於客戶倉庫，7.7米貨架，環氧地坪，需Oracle ERP整合" },
        decision: { status: "partial", detail: "Chayut是中間人。終端客戶決策但不讓外部供應商進場" },
        competitors: { status: "partial", detail: "現有Toyota AGV僅基礎追蹤功能" },
        motivation: { status: "partial", detail: "客戶需要倉庫自動化 — 但非做不可理由未確認" }
      },
      must_act: "partial", must_act_detail: "客戶需求存在但動機強度未確認",
      must_choose_digiwin: "weak", must_choose_detail: "需展示象田品牌AGV優於現有Toyota方案",
      next_action: "Follow up with Chayut — has he reviewed the materials? Schedule online meeting.",
      pain_points: ["終端客戶限制外部進入", "Chayut工作電腦壞了用個人Gmail", "現有AGV僅基礎追蹤無智能化"],
      stakeholders: [
        { name: "Chayut", role: "物流方案經理", type: "技術評估者/中間人", notes: "辦公室在MD Tower附近Big C Bangna。Toyota email: chayut@ttfl.co.th" },
        { name: "終端客戶", role: "最終決策者", type: "Economic Buyer", notes: "不讓外部進場，完全依賴Chayut" }
      ],
      contacts: [
        { name: "Chayut", phone: "+66625561252", email: "chayut@ttfl.co.th", line: null, role: "物流方案經理" }
      ],
      industry: "物料搬運/物流", fit: "HIGH",
      transcript_date: "2026-03-24",
      call_summary: "2026-03-24: 已寄出Xiangtian Introduction PDF + 抖音影片連結 + Digiwin Thailand About頁面。Email寄至armstrong.wuu@gmail.com，CC chayut@ttfl.co.th + eddiesheu@digiwin.com。等待Chayut審閱後安排線上會議。",
      activity_log: [
        { date: "2026-03-24", action: "寄出Xiangtian資料包(PDF+抖音+About頁面)", outcome: "Email已送達，CC Toyota官方信箱+Eddie", stage_change: null },
        { date: "2026-03-23", action: "詳細技術討論電話", outcome: "確認7.7米貨架、環氧地坪、3度斜坡需求", stage_change: null }
      ]
    },
    {
      id: 5, company: "Chia Tai (เจียไต๋)", person: "Khun Tan", title: "Project Manager",
      stage: "D", days_at_stage: 0, days_since_contact: 0, value: null, confidence: "warm",
      six_elements: {
        timeline: { status: false, detail: "客戶未提及Go-Live時程。今天2PM工廠簡報會議，非上線日期" },
        budget: { status: false, detail: "未知" },
        requirements: { status: "partial", detail: "MES用於生產支援（非WMS — PM已糾正Peter）" },
        decision: { status: "partial", detail: "Khun Tan是PM，但不清楚上面誰核准" },
        competitors: { status: false, detail: "未知" },
        motivation: { status: "partial", detail: "有主動需求在找MES，不是隨便看看" }
      },
      must_act: "partial", must_act_detail: "有主動需求但非做不可理由未明確表述",
      must_choose_digiwin: "weak", must_choose_detail: "今天2PM會議是建立的機會",
      next_action: "2PM factory visit at Chia Tai Omnoi — MES presentation",
      pain_points: ["需要MES進行生產支援", "工廠在Samut Sakhon (Omnoi)"],
      stakeholders: [
        { name: "Khun Tan", role: "專案經理", type: "技術聯絡人", notes: "負責生產支援。工廠在Chia Tai Omnoi, Samut Sakhon" },
        { name: "海外顧問", role: "鼎捷產品專家", type: "內部資源", notes: "本週訪泰，行程緊湊" }
      ],
      industry: "農業/種子/製造", fit: "HIGH",
      transcript_date: "2026-03-24",
      call_summary: "公司正名：Chia Tai (เจียไต๋ จำกัด)，泰國農業龍頭。工廠位於Omnoi, Samut Sakhon。網站: chiataigroup.com。Tel: 02-491-8191。今天2PM工廠簡報。"
    },
    // JND/Chris Chang removed from pipeline — he is a potential channel partner, not a deal
    {
      id: 7, company: "Standard Manufacturing", person: "Wisanu (Nu)", title: "Technical Production",
      stage: "D", days_at_stage: 0, days_since_contact: 0, value: null, confidence: "warm",
      six_elements: {
        timeline: { status: false, detail: "未知" },
        budget: { status: false, detail: "未知" },
        requirements: { status: "partial", detail: "對倉庫自動化有興趣" },
        decision: { status: false, detail: "老闆是決策者，需在場才能簡報" },
        competitors: { status: false, detail: "未知" },
        motivation: { status: false, detail: "未確認" }
      },
      must_act: "weak", must_act_detail: "未確認",
      must_choose_digiwin: "weak", must_choose_detail: "未建立",
      next_action: "Call Wisanu next week on 096-963-0735",
      pain_points: ["對倉庫自動化有興趣但細節不明"],
      stakeholders: [
        { name: "Wisanu (Nu)", role: "技術生產", type: "聯絡窗口", notes: "之前跟中國業務在展會談過" },
        { name: "老闆", role: "決策者", type: "Economic Buyer", notes: "需在場才能做簡報" }
      ],
      industry: "製造業", fit: "HIGH",
      transcript_date: "2026-03-23",
      call_summary: "簡短跟進電話。Wisanu會跟秘書確認老闆時間。Peter承諾下週回電。"
    },
    {
      id: 8, company: "Sitthinon Trading", person: "Suwit Boonyaritkit", title: "Owner's Brother",
      stage: "E", days_at_stage: 0, days_since_contact: 0, value: null, confidence: "cold",
      six_elements: {
        timeline: { status: false, detail: "未知" },
        budget: { status: false, detail: "未知" },
        requirements: { status: false, detail: "貿易公司，是否有自動化需求不確定" },
        decision: { status: false, detail: "Suwit是老闆弟弟，委派給採購部" },
        competitors: { status: false, detail: "未知" },
        motivation: { status: false, detail: "未確認" }
      },
      must_act: "weak", must_act_detail: "未確認",
      must_choose_digiwin: "weak", must_choose_detail: "未建立",
      next_action: "Wait for purchasing dept to call",
      pain_points: [],
      stakeholders: [
        { name: "Suwit", role: "老闆弟弟", type: "執行層", notes: "會說一些中文。IATF 16949認證" },
        { name: "採購部", role: "評估者", type: "待聯繫", notes: "Suwit說會讓他們打電話給Peter" }
      ],
      industry: "汽車零件/貿易", fit: "MEDIUM",
      transcript_date: "2026-03-23",
      call_summary: "展會跟進電話。Suwit快速理解（用中文詞彙確認），委派給採購部。Peter等候回電。"
    },
    {
      id: 9, company: "Thai Laminate Manufacturer", person: "Manop Tonsaktragoon", title: "QA Division Manager",
      stage: "E", days_at_stage: 0, days_since_contact: 0, value: null, confidence: "cold",
      six_elements: {
        timeline: { status: false, detail: "未知" },
        budget: { status: false, detail: "未知" },
        requirements: { status: false, detail: "可能需要WMS。目前用SAP" },
        decision: { status: false, detail: "倉庫/MC經理是目標決策者（非Manop）" },
        competitors: { status: false, detail: "現用SAP（版本未知）" },
        motivation: { status: false, detail: "未確認" }
      },
      must_act: "weak", must_act_detail: "未確認",
      must_choose_digiwin: "weak", must_choose_detail: "未建立",
      next_action: "Wait for Warehouse Manager callback. DO NOT call Manop again.",
      pain_points: [],
      stakeholders: [
        { name: "Manop", role: "品質保證部經理", type: "錯誤聯絡人", notes: "對電話感到不耐煩，請勿再打" },
        { name: "倉庫/MC經理", role: "目標決策者", type: "待聯繫", notes: "Manop已轉交Peter資訊" }
      ],
      industry: "層壓板製造", fit: "HIGH",
      transcript_date: "2026-03-23",
      call_summary: "冷淡的陌生電話。Manop是QA部門，非倉庫。已轉交Peter資訊給倉庫經理但拒絕提供直接聯繫方式。Peter試圖轉向ERP話題但被請求結束通話。"
    },
    {
      id: 10, company: "Daisae Metrology", person: "Sirimon Namsai", title: "Sales Online & Marking",
      stage: "E", days_at_stage: 0, days_since_contact: 0, value: null, confidence: "warm",
      six_elements: {
        timeline: { status: false, detail: "未知" },
        budget: { status: false, detail: "未知" },
        requirements: { status: false, detail: "未知" },
        decision: { status: false, detail: "未知" },
        competitors: { status: false, detail: "未知" },
        motivation: { status: false, detail: "未知" }
      },
      must_act: "weak", must_act_detail: "未確認",
      must_choose_digiwin: "weak", must_choose_detail: "未建立",
      next_action: "Send intro email — she expressed interest (สนใจ ส่งเมล์)",
      pain_points: [],
      stakeholders: [
        { name: "Sirimon", role: "線上業務/打標", type: "聯絡窗口", notes: "名片手寫：สนใจ ส่งเมล์（有興趣，寄郵件）" }
      ],
      industry: "計量/測量設備", fit: "LOW",
      transcript_date: "2026-03-23",
      call_summary: "名片處理。非製造商但賣給工廠。名片有LINE QR碼。手寫筆記表示有興趣要求寄郵件。"
    },
    {
      id: 11, company: "NutritionProFest", person: "TBD (via LINE)", title: "TBD",
      stage: "D", days_at_stage: 0, days_since_contact: 0, value: null, confidence: "warm",
      six_elements: {
        timeline: { status: false, detail: "未知。工廠已有詳細CAD圖，基礎設施(WiFi AP/CCTV)正在規劃中，代表專案有推進" },
        budget: { status: false, detail: "未知" },
        requirements: { status: true, detail: "AGV/AMR用於5條路線：(1)RM→產線 3次/天 2-3棧板 (2)包材→產線 3次/天 5-10棧板 (3)包材→PickPack 1次/天 3棧板 (4)FG→產線 2次/週 ~3棧板 (5)FG→PickPack 2次/天 3-4棧板。棧板120x100-120cm，500-700kg/趟。需WMS+ERP整合" },
        decision: { status: false, detail: "尚未識別任何聯絡人。僅有LINE帳號" },
        competitors: { status: false, detail: "未知" },
        motivation: { status: "partial", detail: "正在規劃工廠自動化物流（AGV），已有詳細需求規格和CAD圖面。主動在找解決方案" }
      },
      must_act: "partial", must_act_detail: "主動規劃AGV自動化物流，有具體需求規格，代表有內部推動力",
      must_choose_digiwin: "weak", must_choose_detail: "尚未建立。需展示象田AGV+WMS整合優勢",
      next_action: "Contact via LINE — introduce Digiwin AGV+WMS solution, get a named contact person",
      pain_points: [
        "工廠物流需自動化 — 5條多點取放路線需AGV",
        "需要WMS+ERP系統整合",
        "棧板運輸500-700kg，需工業級AGV",
        "廠區4,800平方米，有明確分區(RM/PM/FG/Pick&Pack)"
      ],
      stakeholders: [],
      industry: "食品/營養品OEM製造", fit: "HIGH",
      transcript_date: "2026-03-24",
      call_summary: "從CAD圖面和需求規格書分析。บริษัท นูทริชั่น โปรเฟส จำกัด位於TIP 9工業區(สมุทรปราการ)。OEM食品/營養品製造商。工廠~4,800sqm，有RM1/RM2、PM1-4產線、FG區、Pick&Pack區。已規劃WiFi AP和CCTV基礎設施。需求明確：AGV自動搬運+WMS+ERP整合。尚無聯絡人，僅有LINE帳號。"
    }
  ],

  i_owe: [
    { what: "Confirm Wed 3pm with consultant", to: "Khun Tan", company: "Chia Tai", due: "2026-03-23", status: "overdue", why: "會議2天後，顧問即將離開泰國" },
    { what: "Send profile + brochures + video", to: "Chayut", company: "Toyota Tsusho", due: "2026-03-24", status: "done", why: "✅ 已寄出 2026-03-24 — PDF+抖音+About頁面" },
    { what: "Send follow-up email", to: "Yanisa", company: "Mitsuya Limited", due: "2026-03-24", status: "due_today", why: "70分鐘會議中承諾的跟進" },
    { what: "Send intro email", to: "Sirimon", company: "Daisae Metrology", due: "2026-03-25", status: "upcoming", why: "名片手寫：สนใจ ส่งเมล์" },
    // JND/Chris Chang moved to channel_partners
    { what: "Prepare tailored proposal", to: "Khun Nueng", company: "BFC", due: "2026-03-28", status: "upcoming", why: "七大痛點已確認，報價只有一次機會" },
    { what: "Call to schedule presentation", to: "Petch", company: "Impextraco", due: "2026-03-25", status: "upcoming", why: "新建工廠（四大非做不可理由）" },
    { what: "Call to schedule factory visit", to: "Wisanu", company: "Standard Mfg", due: "2026-03-28", status: "upcoming", why: "等老闆時間確認" }
  ],

  they_owe: [
    { what: "工廠GPS定位", from: "Khun Tan", company: "Chia Tai", follow_up: "2026-03-25" },
    { what: "審閱資料+加LINE", from: "Chayut", company: "Toyota Tsusho", follow_up: "2026-03-28" },
    { what: "安排與叔叔的會面", from: "Yanisa", company: "Mitsuya Limited", follow_up: "2026-03-30" },
    { what: "透過秘書確認老闆時間", from: "Wisanu", company: "Standard Mfg", follow_up: "2026-03-28" },
    { what: "採購部回電Peter", from: "Suwit", company: "Sitthinon Trading", follow_up: "2026-04-01" },
    { what: "倉庫經理回電", from: "Manop", company: "TLM", follow_up: "2026-04-07" },
    // JND/Chris Chang moved to channel_partners
  ],

  hit_list: [
    { rank: 1, action: "Confirm Wed 3pm consultant availability", company: "Chia Tai", why: "會議2天後。顧問即將離開泰國。延誤=失去窗口", score: 38, type: "call" },
    { rank: 2, action: "Send profile + Xiangtian brochures + video to armstrong.wuu@gmail.com", company: "Toyota Tsusho", why: "逾期承諾。Chayut明確要求資料", score: 32, type: "email" },
    { rank: 3, action: "Prepare BFC proposal (WMS + MES + phased pricing)", company: "BFC", why: "七大痛點今天通話確認，勢頭正熱", score: 28, type: "computer" },
    { rank: 4, action: "Send follow-up email to yanisa@mitsuya.co.th", company: "Mitsuya Limited", why: "70分鐘會議中承諾。汽車零件製造，高適配度", score: 25, type: "email" },
    { rank: 5, action: "Call Petch +66954082233 to schedule presentation", company: "Impextraco", why: "新建工廠 — 四大非做不可理由之一", score: 22, type: "call" },
    { rank: 6, action: "Send intro email to sales@daisaemetrology.co.th", company: "Daisae Metrology", why: "名片註明有興趣，要求寄郵件", score: 15, type: "email" },
    // JND/Chris Chang moved to channel_partners
  ],

  metrics: {
    calls_today: 10,
    contacts_added: 20,
    transcripts_processed: 10,
    emails_queued: 7,
    deals_at_d_or_above: 5,
    pipeline_total: null,
    weighted_total: null
  }
  // NOTE: Channel/distributor pipeline is a SEPARATE dashboard — do not mix with direct sales
};
