// Dashboard data — auto-generated by generate_data.py
// Last updated: 2026-03-27T15:00:09+07:00
// Source: Google Sheet (Deals + Actions + Contacts tabs)
const DASHBOARD_DATA = {
  "generated_at": "2026-03-27T15:00:09+07:00",
  "sources": {
    "deals": "ok",
    "actions": "ok",
    "contacts": "ok"
  },
  "target": {
    "annual": 150000000,
    "ytd_closed": 0,
    "currency": "THB"
  },
  "stage_weights": {
    "E": 0.05,
    "D": 0.1,
    "C2": 0.25,
    "C1": 0.5,
    "B": 0.75,
    "A": 0.9
  },
  "stage_sla": {
    "E": 14,
    "D": 30,
    "C2": 30,
    "C1": 45,
    "B": 30,
    "A": 14
  },
  "deals": [
    {
      "id": 1,
      "company": "BFC (Bangkok Fastening)",
      "person": "K. Lek",
      "title": "Purchasing Manager",
      "stage": "D",
      "days_at_stage": 5,
      "days_since_contact": 0,
      "value": null,
      "confidence": "hot",
      "six_elements": {
        "timeline": {
          "status": false,
          "detail": ""
        },
        "budget": {
          "status": "partial",
          "detail": ""
        },
        "requirements": {
          "status": true,
          "detail": ""
        },
        "decision": {
          "status": true,
          "detail": ""
        },
        "competitors": {
          "status": "partial",
          "detail": ""
        },
        "motivation": {
          "status": true,
          "detail": ""
        }
      },
      "must_act": "strong",
      "must_act_detail": "利潤持續外漏、中國競爭者現代化、Oracle系統僅一人維護",
      "must_choose_digiwin": "weak",
      "must_choose_detail": "尚未建立。提案必須說明為何鼎捷優於Oracle升級或SAP",
      "next_action": "Prepare tailored proposal for Khun Nueng",
      "pain_points": [],
      "stakeholders": [],
      "contacts": [],
      "industry": "螺絲/扣件製造",
      "fit": "HIGH",
      "transcript_date": "",
      "call_summary": "深度探詢通話。K.Lek揭露BFC七大痛點。44年家族企業面臨中國競爭壓力。"
    },
    {
      "id": 2,
      "company": "Impextraco",
      "person": "Petch Janbanjong",
      "title": "Project Engineer",
      "stage": "D",
      "days_at_stage": 0,
      "days_since_contact": 0,
      "value": null,
      "confidence": "warm",
      "six_elements": {
        "timeline": {
          "status": "partial",
          "detail": ""
        },
        "budget": {
          "status": false,
          "detail": ""
        },
        "requirements": {
          "status": "partial",
          "detail": ""
        },
        "decision": {
          "status": "partial",
          "detail": ""
        },
        "competitors": {
          "status": false,
          "detail": ""
        },
        "motivation": {
          "status": true,
          "detail": ""
        }
      },
      "must_act": "strong",
      "must_act_detail": "新建工廠無系統（四大非做不可理由之一）",
      "must_choose_digiwin": "weak",
      "must_choose_detail": "尚未建立。需向比利時管理層展示",
      "next_action": "Call Petch Wednesday to schedule presentation",
      "pain_points": [],
      "stakeholders": [
        {
          "name": "Petch Janbanjong",
          "role": "Project Engineer",
          "type": "聯絡窗口",
          "notes": "Email: petch@impextraco.com"
        }
      ],
      "contacts": [
        {
          "name": "Petch Janbanjong",
          "phone": "+66954082233",
          "email": "petch@impextraco.com",
          "line": null,
          "role": "Project Engineer"
        }
      ],
      "industry": "動物飼料/飼料原料",
      "fit": "HIGH",
      "transcript_date": "",
      "call_summary": "比利時公司今年在泰國建新廠。Peter承諾週三回電安排簡報。"
    },
    {
      "id": 3,
      "company": "Mitsuya Limited",
      "person": "Yanisa Danchaivijit",
      "title": "Assistant Managing Director",
      "stage": "D",
      "days_at_stage": 0,
      "days_since_contact": 0,
      "value": null,
      "confidence": "warm",
      "six_elements": {
        "timeline": {
          "status": false,
          "detail": ""
        },
        "budget": {
          "status": false,
          "detail": ""
        },
        "requirements": {
          "status": "partial",
          "detail": ""
        },
        "decision": {
          "status": "partial",
          "detail": ""
        },
        "competitors": {
          "status": false,
          "detail": ""
        },
        "motivation": {
          "status": "partial",
          "detail": ""
        }
      },
      "must_act": "partial",
      "must_act_detail": "中國競爭壓力，但叔叔的抗拒削弱了緊迫性",
      "must_choose_digiwin": "weak",
      "must_choose_detail": "鼎捷不做網站（第一階段非我們的機會）",
      "next_action": "Send follow-up email to yanisa@mitsuya.co.th",
      "pain_points": [],
      "stakeholders": [
        {
          "name": "Yanisa Danchaivijit",
          "role": "Assistant Managing Director",
          "type": "聯絡窗口",
          "notes": "Email: yanisa.danchaivijit@gmail.com"
        },
        {
          "name": "Nattaya Phakkrua",
          "role": "Marketing Co-ordinator",
          "type": "聯絡窗口",
          "notes": "Email: nattaya@mitsuya.co.th"
        }
      ],
      "contacts": [
        {
          "name": "Yanisa Danchaivijit",
          "phone": "+66622929432",
          "email": "yanisa.danchaivijit@gmail.com",
          "line": null,
          "role": "Assistant Managing Director"
        },
        {
          "name": "Nattaya Phakkrua",
          "phone": null,
          "email": "nattaya@mitsuya.co.th",
          "line": null,
          "role": "Marketing Co-ordinator"
        }
      ],
      "industry": "汽車零件製造",
      "fit": "HIGH",
      "transcript_date": "",
      "call_summary": "70分鐘面對面會議。Yanisa揭示深層代際衝突。"
    },
    {
      "id": 4,
      "company": "Toyota Tsusho Forklift",
      "person": "Chayut Kruekamkhao",
      "title": "Logistics Manager",
      "stage": "D",
      "days_at_stage": 0,
      "days_since_contact": 0,
      "value": null,
      "confidence": "warm",
      "six_elements": {
        "timeline": {
          "status": false,
          "detail": ""
        },
        "budget": {
          "status": false,
          "detail": ""
        },
        "requirements": {
          "status": true,
          "detail": ""
        },
        "decision": {
          "status": "partial",
          "detail": ""
        },
        "competitors": {
          "status": "partial",
          "detail": ""
        },
        "motivation": {
          "status": "partial",
          "detail": ""
        }
      },
      "must_act": "partial",
      "must_act_detail": "客戶需求存在但動機強度未確認",
      "must_choose_digiwin": "weak",
      "must_choose_detail": "需展示象田品牌AGV優於現有Toyota方案",
      "next_action": "Follow up with Chayut — has he reviewed the materials?",
      "pain_points": [],
      "stakeholders": [
        {
          "name": "Chayut Kruekamkhao",
          "role": "Manager",
          "type": "聯絡窗口",
          "notes": "Email: chayut@ttfl.co.th"
        }
      ],
      "contacts": [
        {
          "name": "Chayut Kruekamkhao",
          "phone": "+66625561252",
          "email": "chayut@ttfl.co.th",
          "line": null,
          "role": "Manager"
        }
      ],
      "industry": "物料搬運/物流",
      "fit": "HIGH",
      "transcript_date": "",
      "call_summary": "2026-03-24: 已寄出Xiangtian資料包。等待Chayut審閱。"
    },
    {
      "id": 5,
      "company": "Chia Tai (เจียไต๋)",
      "person": "Khun Tan",
      "title": "Project Manager",
      "stage": "D",
      "days_at_stage": 0,
      "days_since_contact": 0,
      "value": null,
      "confidence": "warm",
      "six_elements": {
        "timeline": {
          "status": false,
          "detail": ""
        },
        "budget": {
          "status": false,
          "detail": ""
        },
        "requirements": {
          "status": "partial",
          "detail": ""
        },
        "decision": {
          "status": "partial",
          "detail": ""
        },
        "competitors": {
          "status": false,
          "detail": ""
        },
        "motivation": {
          "status": "partial",
          "detail": ""
        }
      },
      "must_act": "partial",
      "must_act_detail": "有主動需求但非做不可理由未明確表述",
      "must_choose_digiwin": "weak",
      "must_choose_detail": "明天2PM會議是建立的機會",
      "next_action": "3/25 2PM factory visit at Chia Tai Omnoi — MES presentation",
      "pain_points": [],
      "stakeholders": [
        {
          "name": "Pisut Charoenrat",
          "role": "Deputy Production Manager",
          "type": "聯絡窗口",
          "notes": "Email: pisut.ch@chiataigroup.com"
        }
      ],
      "contacts": [
        {
          "name": "Pisut Charoenrat",
          "phone": null,
          "email": "pisut.ch@chiataigroup.com",
          "line": null,
          "role": "Deputy Production Manager"
        }
      ],
      "industry": "農業/種子/製造",
      "fit": "HIGH",
      "transcript_date": "",
      "call_summary": "泰國農業龍頭。工廠位於Omnoi, Samut Sakhon。明天2PM工廠簡報。"
    },
    {
      "id": 7,
      "company": "Standard Manufacturing",
      "person": "Wisanu (Nu)",
      "title": "Technical Production",
      "stage": "D",
      "days_at_stage": 0,
      "days_since_contact": 0,
      "value": null,
      "confidence": "warm",
      "six_elements": {
        "timeline": {
          "status": false,
          "detail": ""
        },
        "budget": {
          "status": false,
          "detail": ""
        },
        "requirements": {
          "status": "partial",
          "detail": ""
        },
        "decision": {
          "status": false,
          "detail": ""
        },
        "competitors": {
          "status": false,
          "detail": ""
        },
        "motivation": {
          "status": false,
          "detail": ""
        }
      },
      "must_act": "weak",
      "must_act_detail": "未確認",
      "must_choose_digiwin": "weak",
      "must_choose_detail": "未建立",
      "next_action": "Call Wisanu next week on 096-963-0735",
      "pain_points": [],
      "stakeholders": [
        {
          "name": "Wisanu Anantapaiboonsiri",
          "role": "Technical Production",
          "type": "聯絡窗口",
          "notes": "Email: wisanuS@standardmanu.com"
        },
        {
          "name": "Winyu Saetang",
          "role": "Engineer Manager",
          "type": "聯絡窗口",
          "notes": "Email: winyu.st@gmail.com"
        }
      ],
      "contacts": [
        {
          "name": "Wisanu Anantapaiboonsiri",
          "phone": null,
          "email": "wisanuS@standardmanu.com",
          "line": null,
          "role": "Technical Production"
        },
        {
          "name": "Winyu Saetang",
          "phone": null,
          "email": "winyu.st@gmail.com",
          "line": null,
          "role": "Engineer Manager"
        }
      ],
      "industry": "製造業",
      "fit": "HIGH",
      "transcript_date": "",
      "call_summary": "簡短跟進電話。Wisanu會跟秘書確認老闆時間。"
    },
    {
      "id": 8,
      "company": "Sitthinon Trading",
      "person": "Suwit Boonyaritkit",
      "title": "Owner's Brother",
      "stage": "E",
      "days_at_stage": 0,
      "days_since_contact": 0,
      "value": null,
      "confidence": "cold",
      "six_elements": {
        "timeline": {
          "status": false,
          "detail": ""
        },
        "budget": {
          "status": false,
          "detail": ""
        },
        "requirements": {
          "status": false,
          "detail": ""
        },
        "decision": {
          "status": false,
          "detail": ""
        },
        "competitors": {
          "status": false,
          "detail": ""
        },
        "motivation": {
          "status": false,
          "detail": ""
        }
      },
      "must_act": "weak",
      "must_act_detail": "未確認",
      "must_choose_digiwin": "weak",
      "must_choose_detail": "未建立",
      "next_action": "Wait for purchasing dept to call",
      "pain_points": [],
      "stakeholders": [
        {
          "name": "Suwit Boonyaritkit",
          "role": "",
          "type": "聯絡窗口",
          "notes": "Email: Suwit@sv-sitthinon.com"
        },
        {
          "name": "Kasorn Tuptim",
          "role": "Purchase",
          "type": "聯絡窗口",
          "notes": "Email: PC1@sv-sitthinon.com"
        }
      ],
      "contacts": [
        {
          "name": "Suwit Boonyaritkit",
          "phone": "+66869806926",
          "email": "Suwit@sv-sitthinon.com",
          "line": null,
          "role": ""
        },
        {
          "name": "Kasorn Tuptim",
          "phone": "+66882059602",
          "email": "PC1@sv-sitthinon.com",
          "line": null,
          "role": "Purchase"
        }
      ],
      "industry": "汽車零件/貿易",
      "fit": "MEDIUM",
      "transcript_date": "",
      "call_summary": "展會跟進電話。Suwit委派給採購部。"
    },
    {
      "id": 9,
      "company": "Thai Laminate Manufacturer",
      "person": "Manop Tonsaktragoon",
      "title": "QA Division Manager",
      "stage": "E",
      "days_at_stage": 0,
      "days_since_contact": 0,
      "value": null,
      "confidence": "cold",
      "six_elements": {
        "timeline": {
          "status": false,
          "detail": ""
        },
        "budget": {
          "status": false,
          "detail": ""
        },
        "requirements": {
          "status": false,
          "detail": ""
        },
        "decision": {
          "status": false,
          "detail": ""
        },
        "competitors": {
          "status": false,
          "detail": ""
        },
        "motivation": {
          "status": false,
          "detail": ""
        }
      },
      "must_act": "weak",
      "must_act_detail": "未確認",
      "must_choose_digiwin": "weak",
      "must_choose_detail": "未建立",
      "next_action": "Wait for Warehouse Manager callback. DO NOT call Manop again.",
      "pain_points": [],
      "stakeholders": [
        {
          "name": "Manop Tonsaktragoon",
          "role": "Quality Assurance Division Manager",
          "type": "聯絡窗口",
          "notes": "Email: manop_ton@tlm.co.th"
        }
      ],
      "contacts": [
        {
          "name": "Manop Tonsaktragoon",
          "phone": "+66898124076",
          "email": "manop_ton@tlm.co.th",
          "line": null,
          "role": "Quality Assurance Division Manager"
        }
      ],
      "industry": "層壓板製造",
      "fit": "HIGH",
      "transcript_date": "",
      "call_summary": "冷淡的陌生電話。已轉交Peter資訊給倉庫經理。"
    },
    {
      "id": 10,
      "company": "Daisae Metrology",
      "person": "Sirimon Namsai",
      "title": "Sales Online & Marking",
      "stage": "E",
      "days_at_stage": 0,
      "days_since_contact": 0,
      "value": null,
      "confidence": "warm",
      "six_elements": {
        "timeline": {
          "status": false,
          "detail": ""
        },
        "budget": {
          "status": false,
          "detail": ""
        },
        "requirements": {
          "status": false,
          "detail": ""
        },
        "decision": {
          "status": false,
          "detail": ""
        },
        "competitors": {
          "status": false,
          "detail": ""
        },
        "motivation": {
          "status": false,
          "detail": ""
        }
      },
      "must_act": "weak",
      "must_act_detail": "未確認",
      "must_choose_digiwin": "weak",
      "must_choose_detail": "未建立",
      "next_action": "Send intro email — she expressed interest",
      "pain_points": [],
      "stakeholders": [
        {
          "name": "Sirimon Namsai",
          "role": "Sales Online & Marking",
          "type": "聯絡窗口",
          "notes": "Email: sales@daisaemetrology.co.th"
        }
      ],
      "contacts": [
        {
          "name": "Sirimon Namsai",
          "phone": "+66643095439",
          "email": "sales@daisaemetrology.co.th",
          "line": null,
          "role": "Sales Online & Marking"
        }
      ],
      "industry": "計量/測量設備",
      "fit": "LOW",
      "transcript_date": "",
      "call_summary": "名片處理。非製造商但賣給工廠。"
    },
    {
      "id": 11,
      "company": "NutritionProFest",
      "person": "TBD (via LINE)",
      "title": "TBD",
      "stage": "D",
      "days_at_stage": 0,
      "days_since_contact": 0,
      "value": null,
      "confidence": "warm",
      "six_elements": {
        "timeline": {
          "status": false,
          "detail": ""
        },
        "budget": {
          "status": false,
          "detail": ""
        },
        "requirements": {
          "status": true,
          "detail": ""
        },
        "decision": {
          "status": false,
          "detail": ""
        },
        "competitors": {
          "status": false,
          "detail": ""
        },
        "motivation": {
          "status": "partial",
          "detail": ""
        }
      },
      "must_act": "partial",
      "must_act_detail": "主動規劃AGV自動化物流",
      "must_choose_digiwin": "weak",
      "must_choose_detail": "尚未建立。需展示象田AGV+WMS整合優勢",
      "next_action": "Contact via LINE — introduce Digiwin AGV+WMS solution",
      "pain_points": [],
      "stakeholders": [],
      "contacts": [],
      "industry": "食品/營養品OEM製造",
      "fit": "HIGH",
      "transcript_date": "",
      "call_summary": "CAD圖面分析。OEM食品製造商。需AGV+WMS+ERP整合。"
    }
  ],
  "i_owe": [
    {
      "what": "Confirm Wed 2pm factory visit",
      "to": "Khun Tan",
      "company": "Chia Tai",
      "due": "2026-03-23",
      "status": "done",
      "why": "✅ 已確認 — 3/25 14:00 工廠簡報，用車已安排"
    },
    {
      "what": "Send profile + brochures + video",
      "to": "Chayut",
      "company": "Toyota Tsusho",
      "due": "2026-03-24",
      "status": "done",
      "why": "✅ 已寄出 — PDF+抖音+About頁面"
    },
    {
      "what": "Send follow-up email",
      "to": "Yanisa",
      "company": "Mitsuya Limited",
      "due": "2026-03-24",
      "status": "overdue",
      "why": "70分鐘會議中承諾的跟進"
    },
    {
      "what": "Send intro email",
      "to": "Sirimon",
      "company": "Daisae Metrology",
      "due": "2026-03-25",
      "status": "overdue",
      "why": "名片手寫：สนใจ ส่งเมล์"
    },
    {
      "what": "Prepare tailored proposal",
      "to": "Khun Nueng",
      "company": "BFC",
      "due": "2026-03-28",
      "status": "upcoming",
      "why": "七大痛點已確認，報價只有一次機會"
    },
    {
      "what": "Call to schedule presentation",
      "to": "Petch",
      "company": "Impextraco",
      "due": "2026-03-25",
      "status": "overdue",
      "why": "新建工廠（四大非做不可理由）"
    },
    {
      "what": "Call to schedule factory visit",
      "to": "Wisanu",
      "company": "Standard Mfg",
      "due": "2026-03-28",
      "status": "upcoming",
      "why": "等老闆時間確認"
    }
  ],
  "they_owe": [
    {
      "what": "工廠GPS定位",
      "from": "Khun Tan",
      "company": "Chia Tai",
      "follow_up": "2026-03-25"
    },
    {
      "what": "審閱資料+加LINE",
      "from": "Chayut",
      "company": "Toyota Tsusho",
      "follow_up": "2026-03-28"
    },
    {
      "what": "安排與叔叔的會面",
      "from": "Yanisa",
      "company": "Mitsuya Limited",
      "follow_up": "2026-03-30"
    },
    {
      "what": "透過秘書確認老闆時間",
      "from": "Wisanu",
      "company": "Standard Mfg",
      "follow_up": "2026-03-28"
    },
    {
      "what": "採購部回電Peter",
      "from": "Suwit",
      "company": "Sitthinon Trading",
      "follow_up": "2026-04-01"
    },
    {
      "what": "倉庫經理回電",
      "from": "Manop",
      "company": "TLM",
      "follow_up": "2026-04-07"
    }
  ],
  "hit_list": [
    {
      "rank": 1,
      "action": "Send follow-up email",
      "company": "Mitsuya Limited",
      "why": "70分鐘會議中承諾的跟進",
      "score": 27,
      "type": "email"
    },
    {
      "rank": 2,
      "action": "Send intro email",
      "company": "Daisae Metrology",
      "why": "名片手寫：สนใจ ส่งเมล์",
      "score": 24,
      "type": "email"
    },
    {
      "rank": 3,
      "action": "Call to schedule presentation",
      "company": "Impextraco",
      "why": "新建工廠（四大非做不可理由）",
      "score": 21,
      "type": "call"
    },
    {
      "rank": 4,
      "action": "Prepare tailored proposal",
      "company": "BFC",
      "why": "七大痛點已確認，報價只有一次機會",
      "score": 18,
      "type": "computer"
    },
    {
      "rank": 5,
      "action": "Call to schedule factory visit",
      "company": "Standard Mfg",
      "why": "等老闆時間確認",
      "score": 15,
      "type": "call"
    }
  ],
  "metrics": {
    "calls_today": 0,
    "contacts_added": 79,
    "transcripts_processed": 0,
    "emails_queued": 2,
    "deals_at_d_or_above": 7,
    "pipeline_total": null,
    "weighted_total": null
  }
};
